sudo: false
dist: xenial
language: python
install:
  - pip install tox

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37

script: tox

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  irc:
    channels:
    - irc.freenode.org#cs-york-dev
    skip_join: true
    use_notice: true
