version: "3"

services:
  bot:
    build: .
    links:
      - mongodb
    volumes:
      - .:/app
    env_file:
      - ./deploy.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/csbot

  mongodb:
    image: mongo:4.1
    volumes:
      - ./mongodb-data:/data/db
