version: "3"

services:
  bot:
    image: alanbriolat/csbot:latest
    links:
      - mongodb
    env_file:
      - ./deploy.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/csbot
    command: csbot.deploy.cfg
    ports:
      - "127.0.0.1:8180:80"
    labels:
      - com.centurylinklabs.watchtower.enable=true

  mongodb:
    image: mongo:4.0
    volumes:
      - ./mongodb-data:/data/db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 120
    restart: always
