version: "3"

services:
  bot:
    build: .
    links:
      - mongodb
    volumes:
      - .:/app
    env_file:
      - ./deploy.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/csbot
    command: ./run_csbot.py csbot.deploy.cfg --rollbar
    ports:
      - "127.0.0.1:8180:80"

  mongodb:
    image: mongo:4.0
    volumes:
      - ./mongodb-data:/data/db
